POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "tests",
    "password": "tests"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "useritems": [],
    "username": "tests",
    "name": "Test",
    "password": "tests"
}

###
POST http://localhost:3001/api/useritems
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RzIiwiaWQiOiI2MGY5ZjhkNzc0NGQxZTkzOTc2MTkwYWQiLCJpYXQiOjE2MjY5OTY4MDUsImV4cCI6MTYyNzAwMDQwNX0.wPfq2DCz1ujDhS0KU4ExeNZODwM5m7g3K3TvtvGtltI

{
    "name": "Kingston HyperX FURY DDR4 RGB",
    "price": 62.95,
    "quantity": 3,
    "category": "Memory",
    "imgPath": "https://i.imgur.com/8L0VQoc.png",
    "imgPreview": "https://i.imgur.com/920tOW9.jpg",
    "productPreview": "https://i.imgur.com/H2hcsGH.png"
}

###
GET http://localhost:3001/api/products/

###
GET http://localhost:3001/api/cartitems/

###
GET http://localhost:3001/api/cartitems/60f747cb73c66f0015453a94

###
GET http://localhost:3001/api/cartitems/sdfgsdfg435

###
GET http://localhost:3001/api/products/60ef5ae3254d9a2b86750a09

###
POST http://localhost:3001/api/cartitems
Content-Type: application/json

{
    "name": "Fractal Design Meshify C",
    "price": 95.99,
    "quantity": 1,
    "category": "Case",
    "imgPath": "https://i.imgur.com/b3ieUZw.jpg",
    "imgPreview": "https://i.imgur.com/iOrrWY6.jpg",
    "productPreview": "https://i.imgur.com/x4CmFCt.png"
}

###
DELETE http://localhost:3001/api/cartitems/60f74c5673c66f0015453afe

###
PUT http://localhost:3001/api/cartitems/60f77ab1435492001c03e1c8
Content-Type: application/json

{
    "name": "Fractal Design Meshify C",
    "price": 95.99,
    "quantity": 4,
    "category": "Case",
    "imgPath": "https://i.imgur.com/b3ieUZw.jpg",
    "imgPreview": "https://i.imgur.com/iOrrWY6.jpg",
    "productPreview": "https://i.imgur.com/x4CmFCt.png"
}


